"""add fee_plans and student_fees tables

Revision ID: 979646623346
Revises: a7e58e0721ea
Create Date: 2026-08-14 17:47:37.313079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979646623346'
down_revision = 'a7e58e0721ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('monthly_amount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_plans_student_id'), ['student_id'], unique=False)

    op.create_table('student_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_plan_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', name='feestatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fee_plan_id'], ['fee_plans.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_plan_id', 'cycle', name='uq_student_fee_plan_cycle')
    )
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_fees_cycle'), ['cycle'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_fee_plan_id'), ['fee_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_razorpay_order_id'), ['razorpay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_fees_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_fees_status'))
        batch_op.drop_index(batch_op.f('ix_student_fees_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_student_fees_fee_plan_id'))
        batch_op.drop_index(batch_op.f('ix_student_fees_due_date'))
        batch_op.drop_index(batch_op.f('ix_student_fees_cycle'))

    op.drop_table('student_fees')
    with op.batch_alter_table('fee_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_plans_student_id'))

    op.drop_table('fee_plans')
    # ### end Alembic commands ###
