"""add max_marks to homework and tests

Revision ID: a7e58e0721ea
Revises: 78a9837cc118
Create Date: 2026-08-14 13:52:56.014979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e58e0721ea'
down_revision = '78a9837cc118'
branch_labels = None
depends_on = None

# Every row created before this migration was graded on an implicit 100-point
# scale (that's what the analytics service assumed when it averaged raw
# marks) -- 100 is a backfill value consistent with existing data, not an
# arbitrary guess.
_BACKFILL_MAX_MARKS = 100


def upgrade():
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_marks', sa.Integer(), nullable=True))

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_marks', sa.Integer(), nullable=True))

    conn = op.get_bind()
    conn.exec_driver_sql(f"UPDATE homework SET max_marks = {_BACKFILL_MAX_MARKS} WHERE max_marks IS NULL")
    conn.exec_driver_sql(f"UPDATE tests SET max_marks = {_BACKFILL_MAX_MARKS} WHERE max_marks IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('max_marks')

    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_column('max_marks')

    # ### end Alembic commands ###
