"""add student face_embedding column

Revision ID: c52b6ccecccd
Revises: 688d731de8b1
Create Date: 2026-08-02 14:44:47.877926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52b6ccecccd'
down_revision = '688d731de8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_embedding', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('face_embedding')

    # ### end Alembic commands ###
