"""add resources table

Revision ID: d675a9223af8
Revises: 2db63e046d59
Create Date: 2026-07-25 15:19:14.523974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd675a9223af8'
down_revision = '2db63e046d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('NOTE', 'PDF', 'IMAGE', 'QUESTION_PAPER', 'ANSWER_KEY', name='resourcetype'), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_resources_type'))
        batch_op.drop_index(batch_op.f('ix_resources_subject_id'))
        batch_op.drop_index(batch_op.f('ix_resources_class_id'))

    op.drop_table('resources')
    # ### end Alembic commands ###
